# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               J!nGanG
tagline:             ' work hard, play harder'
description:         'Back to Dev, I am J!nGanG'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              J!nGanG
  url:               http://117go.com
  email:             jingang0121@gmail.com

# Custom vars
version:             1.0.0

# gems
gems: [jekyll-paginate]
